# Generated by Django 4.0.4 on 2023-07-27 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ark', '0005_alter_key_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ark',
            name='shoulder',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='ark.shoulder'),
        ),
        migrations.AlterField(
            model_name='key',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
