# Generated by Django 4.0.4 on 2023-07-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark', '0006_alter_ark_shoulder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoulder',
            name='shoulder',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
