# Generated by Django 4.0.4 on 2023-08-09 22:25

import ark.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark', '0007_alter_shoulder_shoulder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoulder',
            name='shoulder',
            field=models.CharField(max_length=50, validators=[ark.forms.validate_shoulder]),
        ),
        migrations.AlterUniqueTogether(
            name='shoulder',
            unique_together={('shoulder', 'naan')},
        ),
    ]
